import { ruleDefinitions } from "../rules/ruleDefinitions.js";
import type { Libraries } from "../types.js";

export const defaultLibraries: Libraries = {
  volumeToCount: [
    { content_type: "socks_regular", volume_level: "small", count: 8, count_unit: "pairs" },
    { content_type: "socks_regular", volume_level: "medium", count: 16, count_unit: "pairs" },
    { content_type: "socks_regular", volume_level: "large", count: 24, count_unit: "pairs" },
    { content_type: "panties", volume_level: "small", count: 6, count_unit: "items" },
    { content_type: "panties", volume_level: "medium", count: 10, count_unit: "items" },
    { content_type: "panties", volume_level: "large", count: 16, count_unit: "items" },
    { content_type: "boxers", volume_level: "small", count: 5, count_unit: "items" },
    { content_type: "boxers", volume_level: "medium", count: 8, count_unit: "items" },
    { content_type: "boxers", volume_level: "large", count: 12, count_unit: "items" },
    { content_type: "bras", volume_level: "small", count: 3, count_unit: "items" },
    { content_type: "bras", volume_level: "medium", count: 6, count_unit: "items" },
    { content_type: "bras", volume_level: "large", count: 10, count_unit: "items" },
    { content_type: "tights", volume_level: "small", count: 3, count_unit: "items" },
    { content_type: "tights", volume_level: "medium", count: 8, count_unit: "items" },
    { content_type: "tights", volume_level: "large", count: 12, count_unit: "items" },
    { content_type: "tshirts", volume_level: "small", count: 5, count_unit: "items" },
    { content_type: "tshirts", volume_level: "medium", count: 10, count_unit: "items" },
    { content_type: "tshirts", volume_level: "large", count: 15, count_unit: "items" },
    { content_type: "jeans", volume_level: "small", count: 2, count_unit: "items" },
    { content_type: "jeans", volume_level: "medium", count: 4, count_unit: "items" },
    { content_type: "jeans", volume_level: "large", count: 6, count_unit: "items" },
    { content_type: "sport_tops", volume_level: "small", count: 4, count_unit: "items" },
    { content_type: "sport_tops", volume_level: "medium", count: 6, count_unit: "items" },
    { content_type: "sport_tops", volume_level: "large", count: 10, count_unit: "items" },
    { content_type: "thermals", volume_level: "small", count: 2, count_unit: "sets" },
    { content_type: "thermals", volume_level: "medium", count: 4, count_unit: "sets" },
    { content_type: "thermals", volume_level: "large", count: 6, count_unit: "sets" },
    { content_type: "pajamas", volume_level: "small", count: 2, count_unit: "items" },
    { content_type: "pajamas", volume_level: "medium", count: 4, count_unit: "items" },
    { content_type: "pajamas", volume_level: "large", count: 6, count_unit: "items" },
    { content_type: "nightgowns", volume_level: "small", count: 2, count_unit: "items" },
    { content_type: "nightgowns", volume_level: "medium", count: 4, count_unit: "items" },
    { content_type: "nightgowns", volume_level: "large", count: 6, count_unit: "items" },
    { content_type: "longsleeves", volume_level: "small", count: 3, count_unit: "items" },
    { content_type: "longsleeves", volume_level: "medium", count: 6, count_unit: "items" },
    { content_type: "longsleeves", volume_level: "large", count: 10, count_unit: "items" },
    { content_type: "sweaters", volume_level: "small", count: 2, count_unit: "items" },
    { content_type: "sweaters", volume_level: "medium", count: 4, count_unit: "items" },
    { content_type: "sweaters", volume_level: "large", count: 7, count_unit: "items" },
    { content_type: "leggings", volume_level: "small", count: 3, count_unit: "items" },
    { content_type: "leggings", volume_level: "medium", count: 6, count_unit: "items" },
    { content_type: "leggings", volume_level: "large", count: 10, count_unit: "items" },
    { content_type: "shorts", volume_level: "small", count: 3, count_unit: "items" },
    { content_type: "shorts", volume_level: "medium", count: 5, count_unit: "items" },
    { content_type: "shorts", volume_level: "large", count: 8, count_unit: "items" },
    { content_type: "belts", volume_level: "small", count: 2, count_unit: "items" },
    { content_type: "belts", volume_level: "medium", count: 4, count_unit: "items" },
    { content_type: "belts", volume_level: "large", count: 7, count_unit: "items" },
    { content_type: "jewelry_large", volume_level: "small", count: 3, count_unit: "items" },
    { content_type: "jewelry_large", volume_level: "medium", count: 8, count_unit: "items" },
    { content_type: "jewelry_large", volume_level: "large", count: 15, count_unit: "items" },
    { content_type: "jewelry_small", volume_level: "small", count: 10, count_unit: "items" },
    { content_type: "jewelry_small", volume_level: "medium", count: 25, count_unit: "items" },
    { content_type: "jewelry_small", volume_level: "large", count: 50, count_unit: "items" },
    { content_type: "scarves", volume_level: "small", count: 2, count_unit: "items" },
    { content_type: "scarves", volume_level: "medium", count: 5, count_unit: "items" },
    { content_type: "scarves", volume_level: "large", count: 10, count_unit: "items" },
    { content_type: "ties", volume_level: "small", count: 3, count_unit: "items" },
    { content_type: "ties", volume_level: "medium", count: 7, count_unit: "items" },
    { content_type: "ties", volume_level: "large", count: 12, count_unit: "items" },
    { content_type: "swimwear", volume_level: "small", count: 2, count_unit: "items" },
    { content_type: "swimwear", volume_level: "medium", count: 4, count_unit: "items" },
    { content_type: "swimwear", volume_level: "large", count: 7, count_unit: "items" }
  ],
  storageUnitProfile: [
    { content_type: "socks_regular", storage_category: "underwear", storage_method: "roll", primary_division: "cells", alternative_division: "open", preferred_rigidity: "soft", unit_w_cm: 6, unit_d_cm: 6, unit_h_cm: 7, needs_item_gap: true, item_gap: 0.5, item_gap_if_open: 0, side_clear: 0.5, fb_clear: 0.5, h_clear: 1, access_frequency: 8, can_rotate: true, can_split: false, open_fallback_allowed: true, open_fallback_rank: 2, open_storage_penalty: "medium", open_fallback_notes: "Можно хранить роллами в открытой секции, но ячейки лучше удерживают пары." },
    { content_type: "panties", storage_category: "underwear", storage_method: "folded_squares_thin", primary_division: "cells", alternative_division: "open", preferred_rigidity: "soft", unit_w_cm: 10, unit_d_cm: 3, unit_h_cm: 6, needs_item_gap: true, item_gap: 0.5, item_gap_if_open: 0, side_clear: 0.5, fb_clear: 0.5, h_clear: 1, access_frequency: 9, can_rotate: true, can_split: false, open_fallback_allowed: true, open_fallback_rank: 1, open_storage_penalty: "low", open_fallback_notes: "Можно сложить прямоугольниками и поставить в 2–3 ряда в открытой секции." },
    { content_type: "boxers", storage_category: "underwear", storage_method: "folded_squares_medium", primary_division: "cells", alternative_division: "open", preferred_rigidity: "soft", unit_w_cm: 14, unit_d_cm: 4, unit_h_cm: 7, needs_item_gap: true, item_gap: 0.5, item_gap_if_open: 0.3, side_clear: 0.5, fb_clear: 0.5, h_clear: 1, access_frequency: 8, can_rotate: true, can_split: false, open_fallback_allowed: true, open_fallback_rank: 2, open_storage_penalty: "medium" },
    { content_type: "bras", storage_category: "underwear", storage_method: "delicate_stack", primary_division: "slots", alternative_division: "open", preferred_rigidity: "semi_rigid", unit_w_cm: 28, unit_d_cm: 4.5, unit_h_cm: 12, needs_item_gap: true, item_gap: 0.5, item_gap_if_open: 0.5, side_clear: 0.5, fb_clear: 0.5, h_clear: 1, access_frequency: 6, can_rotate: false, can_split: false, max_slot_lanes: 2, slot_lane_gap_cm: 1, split_strategy: "balance_by_depth", notes: "Не сжимать чашки.", open_fallback_allowed: false, open_fallback_rank: 8, open_storage_penalty: "high", soft_height_warning_allowed: true, max_soft_height_overflow_cm: 5, soft_height_warning_code: "deformation_risk" },
    { content_type: "tights", storage_category: "underwear", storage_method: "roll", primary_division: "cells", alternative_division: "open", preferred_rigidity: "soft", unit_w_cm: 7, unit_d_cm: 4, unit_h_cm: 8, needs_item_gap: true, item_gap: 0.5, item_gap_if_open: 0, side_clear: 0.5, fb_clear: 0.5, h_clear: 1, access_frequency: 7, can_rotate: true, can_split: false, open_fallback_allowed: true, open_fallback_rank: 2, open_storage_penalty: "medium", open_fallback_notes: "Можно хранить свернутыми в открытой секции; ячейки лучше разделяют пары колготок." },
    { content_type: "tshirts", storage_category: "soft_clothes", storage_method: "folded_squares_medium", primary_division: "slots", alternative_division: "open", preferred_rigidity: "soft", unit_w_cm: 21, unit_d_cm: 4.5, unit_h_cm: 15, needs_item_gap: true, item_gap: 0.5, item_gap_if_open: 0.3, side_clear: 0.5, fb_clear: 0.5, h_clear: 1, access_frequency: 8, can_rotate: true, can_split: false, open_fallback_allowed: true, open_fallback_rank: 3, open_storage_penalty: "medium", soft_height_warning_allowed: true, max_soft_height_overflow_cm: 5, soft_height_warning_code: "compressed_storage" },
    { content_type: "jeans", storage_category: "soft_clothes", storage_method: "folded_squares_bulky", primary_division: "slots", alternative_division: "open", preferred_rigidity: "semi_rigid", unit_w_cm: 28, unit_d_cm: 9, unit_h_cm: 19, needs_item_gap: true, item_gap: 1, item_gap_if_open: 0.5, side_clear: 0.5, fb_clear: 0.5, h_clear: 1, access_frequency: 5, can_rotate: false, can_split: false, open_fallback_allowed: false, open_fallback_rank: 9, open_storage_penalty: "high" },
    { content_type: "sport_tops", storage_category: "underwear", storage_method: "flat", primary_division: "cells", alternative_division: "open", preferred_rigidity: "rigid", unit_w_cm: 15, unit_d_cm: 4, unit_h_cm: 10, needs_item_gap: false, item_gap: 0, item_gap_if_open: 0.5, side_clear: 0, fb_clear: 0, h_clear: 0, access_frequency: "medium", can_rotate: true, can_split: false, open_fallback_allowed: true, open_fallback_rank: 4, open_storage_penalty: "medium", open_fallback_notes: "Open fallback allowed only if needed; folded sports tops can be grouped, but cells give better separation.", notes: "1 шт = 1 ячейка", soft_height_warning_allowed: true, max_soft_height_overflow_cm: 5, soft_height_warning_code: "compressed_storage" },
    { content_type: "thermals", storage_category: "underwear", storage_method: "folded_squares_bulky", primary_division: "slots", alternative_division: "open", preferred_rigidity: "semi_rigid", unit_w_cm: 22, unit_d_cm: 13, unit_h_cm: 15, needs_item_gap: true, item_gap: 1, item_gap_if_open: 1, side_clear: 1, fb_clear: 1, h_clear: 1, access_frequency: "low", can_rotate: true, can_split: false, open_fallback_allowed: true, open_fallback_rank: 4, open_storage_penalty: "medium", open_fallback_notes: "Open fallback allowed: thermal sets are bulky and seasonal; open section is acceptable if separated from delicate items.", notes: "Объёмный сложенный квадрат, сезонное", soft_height_warning_allowed: true, max_soft_height_overflow_cm: 5, soft_height_warning_code: "compressed_storage" },
    { content_type: "pajamas", storage_category: "underwear", storage_method: "folded_squares_bulky", primary_division: "slots", alternative_division: "open", preferred_rigidity: "rigid", unit_w_cm: 22, unit_d_cm: 8, unit_h_cm: 19, needs_item_gap: true, item_gap: 1, item_gap_if_open: 1, side_clear: 1, fb_clear: 1, h_clear: 1, access_frequency: "medium", can_rotate: true, can_split: false, open_fallback_allowed: true, open_fallback_rank: 4, open_storage_penalty: "medium", open_fallback_notes: "Open fallback allowed if volume is bulky; slots keep folded pajamas easier to see.", notes: "Сложен квадратом, стоит вертикально", soft_height_warning_allowed: true, max_soft_height_overflow_cm: 5, soft_height_warning_code: "compressed_storage" },
    { content_type: "nightgowns", storage_category: "underwear", storage_method: "folded_squares_medium", primary_division: "slots", alternative_division: "open", preferred_rigidity: "rigid", unit_w_cm: 20, unit_d_cm: 8, unit_h_cm: 10, needs_item_gap: true, item_gap: 0.5, item_gap_if_open: 0.5, side_clear: 0.5, fb_clear: 0.5, h_clear: 0.5, access_frequency: "medium", can_rotate: true, can_split: false, open_fallback_allowed: true, open_fallback_rank: 4, open_storage_penalty: "low", open_fallback_notes: "Open fallback allowed: thin nightgowns can be grouped without much structure risk.", notes: "Сложена квадратом, стоит вертикально", soft_height_warning_allowed: true, max_soft_height_overflow_cm: 5, soft_height_warning_code: "compressed_storage" },
    { content_type: "longsleeves", storage_category: "soft_clothes", storage_method: "folded_squares_thin", primary_division: "slots", alternative_division: "open", preferred_rigidity: "rigid", unit_w_cm: 20, unit_d_cm: 8, unit_h_cm: 10, needs_item_gap: true, item_gap: 0.5, item_gap_if_open: 0.5, side_clear: 0.5, fb_clear: 0.5, h_clear: 0.5, access_frequency: "medium", can_rotate: true, can_split: false, open_fallback_allowed: true, open_fallback_rank: 4, open_storage_penalty: "medium", open_fallback_notes: "Open fallback allowed if needed; slots better preserve vertical folded access.", notes: "KonMari вертикально" },
    { content_type: "sweaters", storage_category: "soft_clothes", storage_method: "folded_squares_bulky", primary_division: "slots", alternative_division: "open", preferred_rigidity: "rigid", unit_w_cm: 28, unit_d_cm: 9, unit_h_cm: 19, needs_item_gap: true, item_gap: 1, item_gap_if_open: 1, side_clear: 1, fb_clear: 1, h_clear: 1, access_frequency: "medium", can_rotate: true, can_split: false, open_fallback_allowed: true, open_fallback_rank: 6, open_storage_penalty: "high", open_fallback_notes: "Open fallback is high penalty: bulky sweaters can lose structure or compress nearby items.", notes: "Только плотные, не объёмные" },
    { content_type: "leggings", storage_category: "soft_clothes", storage_method: "folded_squares_thin", primary_division: "slots", alternative_division: "open", preferred_rigidity: "rigid", unit_w_cm: 18, unit_d_cm: 8, unit_h_cm: 10, needs_item_gap: true, item_gap: 0.5, item_gap_if_open: 0.5, side_clear: 0.5, fb_clear: 0.5, h_clear: 0.5, access_frequency: "medium", can_rotate: true, can_split: false, open_fallback_allowed: true, open_fallback_rank: 3, open_storage_penalty: "medium", open_fallback_notes: "Open fallback allowed: leggings are flexible, but slots keep the stack visible.", notes: "Тонкий сложенный блок", soft_height_warning_allowed: true, max_soft_height_overflow_cm: 5, soft_height_warning_code: "compressed_storage" },
    { content_type: "shorts", storage_category: "soft_clothes", storage_method: "folded_squares_medium", primary_division: "slots", alternative_division: "open", preferred_rigidity: "rigid", unit_w_cm: 20, unit_d_cm: 8, unit_h_cm: 10, needs_item_gap: true, item_gap: 0.5, item_gap_if_open: 0.5, side_clear: 0.5, fb_clear: 0.5, h_clear: 0.5, access_frequency: "medium", can_rotate: true, can_split: false, open_fallback_allowed: true, open_fallback_rank: 4, open_storage_penalty: "medium", open_fallback_notes: "Open fallback allowed if needed; slots keep folded shorts easier to browse.", notes: "Средний сложенный блок" },
    { content_type: "belts", storage_category: "accessories", storage_method: "roll", primary_division: "cells", alternative_division: "open", preferred_rigidity: "rigid", unit_w_cm: 8, unit_d_cm: 8, unit_h_cm: 5, needs_item_gap: false, item_gap: 0, item_gap_if_open: 0.5, side_clear: 0, fb_clear: 0, h_clear: 0, access_frequency: "low", can_rotate: true, can_split: false, open_fallback_allowed: true, open_fallback_rank: 3, open_storage_penalty: "medium", open_fallback_notes: "Open fallback allowed for rolled belts if visibility is acceptable.", notes: "Свёрнут в кольцо" },
    { content_type: "jewelry_large", storage_category: "accessories", storage_method: "flat", primary_division: "cells", alternative_division: "open", preferred_rigidity: "rigid", unit_w_cm: 8, unit_d_cm: 8, unit_h_cm: 4, needs_item_gap: false, item_gap: 0, item_gap_if_open: 0.5, side_clear: 0, fb_clear: 0, h_clear: 0, access_frequency: "low", can_rotate: true, can_split: false, open_fallback_allowed: false, open_fallback_rank: 8, open_storage_penalty: "high", open_fallback_notes: "Avoid open fallback for large jewelry: tangling and mixing risk; use cells.", notes: "Браслеты, цепочки" },
    { content_type: "jewelry_small", storage_category: "accessories", storage_method: "flat", primary_division: "cells", alternative_division: "open", preferred_rigidity: "rigid", unit_w_cm: 3, unit_d_cm: 3, unit_h_cm: 2.5, needs_item_gap: false, item_gap: 0, item_gap_if_open: 0.2, side_clear: 0, fb_clear: 0, h_clear: 0, access_frequency: "low", can_rotate: true, can_split: true, open_fallback_allowed: false, open_fallback_rank: 9, open_storage_penalty: "high", open_fallback_notes: "Avoid open fallback for small jewelry: high loss/mixing risk; use cells.", notes: "Серьги, кольца; мелкие ячейки 3×3" },
    { content_type: "scarves", storage_category: "accessories", storage_method: "roll", primary_division: "cells", alternative_division: "open", preferred_rigidity: "rigid", unit_w_cm: 15, unit_d_cm: 5, unit_h_cm: 8, needs_item_gap: false, item_gap: 0, item_gap_if_open: 0.5, side_clear: 0, fb_clear: 0, h_clear: 0, access_frequency: "low", can_rotate: true, can_split: false, open_fallback_allowed: true, open_fallback_rank: 3, open_storage_penalty: "medium", open_fallback_notes: "Open fallback allowed for rolled scarves if visibility is acceptable.", notes: "Свёрнуты рулоном" },
    { content_type: "ties", storage_category: "accessories", storage_method: "roll", primary_division: "cells", alternative_division: "open", preferred_rigidity: "rigid", unit_w_cm: 8, unit_d_cm: 8, unit_h_cm: 4, needs_item_gap: false, item_gap: 0, item_gap_if_open: 0.5, side_clear: 0, fb_clear: 0, h_clear: 0, access_frequency: "low", can_rotate: true, can_split: false, open_fallback_allowed: true, open_fallback_rank: 3, open_storage_penalty: "medium", open_fallback_notes: "Open fallback allowed for rolled ties if visibility is acceptable.", notes: "Свёрнут в кольцо" },
    { content_type: "swimwear", storage_category: "accessories", storage_method: "flat", primary_division: "cells", alternative_division: "open", preferred_rigidity: "rigid", unit_w_cm: 15, unit_d_cm: 5, unit_h_cm: 8, needs_item_gap: false, item_gap: 0, item_gap_if_open: 0.5, side_clear: 0, fb_clear: 0, h_clear: 0, access_frequency: "low", can_rotate: true, can_split: false, open_fallback_allowed: true, open_fallback_rank: 2, open_storage_penalty: "low", open_fallback_notes: "Open fallback allowed: swimwear is flexible and can be grouped compactly.", notes: "Тонкий сложенный блок, сезонное" }
  ],
  zoneLayoutOptions: [
    { option_id: "cells_2x2", division_type: "cells", calculation_mode: "fixed_grid", count_min: 1, count_max: 4, cols: 2, rows: 2, capacity: 4 },
    { option_id: "cells_2x3", division_type: "cells", calculation_mode: "fixed_grid", count_min: 5, count_max: 6, cols: 2, rows: 3, capacity: 6 },
    { option_id: "cells_3x3", division_type: "cells", calculation_mode: "fixed_grid", count_min: 7, count_max: 9, cols: 3, rows: 3, capacity: 9 },
    { option_id: "cells_3x4", division_type: "cells", calculation_mode: "fixed_grid", count_min: 10, count_max: 12, cols: 3, rows: 4, capacity: 12 },
    { option_id: "cells_4x4", division_type: "cells", calculation_mode: "fixed_grid", count_min: 13, count_max: 16, cols: 4, rows: 4, capacity: 16 },
    { option_id: "cells_4x5", division_type: "cells", calculation_mode: "fixed_grid", count_min: 17, count_max: 20, cols: 4, rows: 5, capacity: 20 },
    { option_id: "cells_5x5", division_type: "cells", calculation_mode: "fixed_grid", count_min: 21, count_max: 25, cols: 5, rows: 5, capacity: 25 },
    { option_id: "cells_5x6", division_type: "cells", calculation_mode: "fixed_grid", count_min: 26, count_max: 30, cols: 5, rows: 6, capacity: 30 },
    { option_id: "slots_single_row", division_type: "slots", calculation_mode: "linear_depth", count_min: 1, count_max: 99 },
    { option_id: "slots_multi_lane_auto", division_type: "slots", calculation_mode: "linear_depth_split", count_min: 7, count_max: 20, notes: "Split slot-stored items into multiple parallel lanes when one lane exceeds drawer depth." },
    { option_id: "open_single_section", division_type: "open", calculation_mode: "open_capacity_in_box", count_min: 1, count_max: 999 }
  ],
  layoutRules: { rule_ids: ["D01", "D02", "D03", "D04", "D04b", "D05", "D06"], reserve_policy: "reserve_to_edge_or_open_zone", definitions: ruleDefinitions },
  ruleDefinitions,
  skuCatalog: []
};
