// Dev-only: tests SKU matching against the real catalog extracted from E_SKU_catalog_v0605.xlsx
// Usage: npx tsx engine/tools/runSkuMatchingTest.ts
// Requires: /tmp/sku_catalog_raw.json (generated by: python3 scripts/extractSkuCatalog.py)

import { readFileSync } from "node:fs";
import { runUmestnoEngine } from "../index.js";
import { defaultLibraries } from "../libraries/defaultLibraries.js";
import type { SkuCatalogRow, DivisionType } from "../types.js";

// ─── Load catalog from extracted JSON ───────────────────────────────────────

function loadCatalog(): SkuCatalogRow[] {
  const raw: Record<string, string | null>[] = JSON.parse(readFileSync("/tmp/sku_catalog_raw.json", "utf8"));

  return raw
    .filter(r => r.division_type && ["cells", "slots", "open"].includes(r.division_type))
    .map(r => ({
      sku_id: r.sku_id ?? "",
      division_type: r.division_type as DivisionType,
      rigidity: r.rigidity ?? "",
      width_cm: parseFloat(r.width_cm ?? "0"),
      depth_cm: parseFloat(r.depth_cm ?? "0"),
      height_cm: parseFloat(r.height_cm ?? "0"),
      capacity_units: r.capacity_units != null ? parseInt(r.capacity_units) : 0,
      color_group: r.color_group ?? undefined,
      color_normalized: r.color_normalized ?? undefined,
      material_group: r.material_group ?? undefined,
      availability_status: r.availability_status === "unavailable" ? "unavailable" : "available",
      product_title: r.product_title ?? "",
      source_platform: r.source_platform ?? undefined,
      product_url: r.product_url ?? undefined,
      price_rub: r.price != null ? parseFloat(r.price) : undefined,
    }));
}

// ─── Test scenarios ──────────────────────────────────────────────────────────

const scenarios = [
  {
    name: "Base 90×45×15 — носки / бюстгальтеры / трусы",
    input: { drawer_width_cm: 90, drawer_depth_cm: 45, drawer_height_cm: 15, storage_category: "underwear" as const, item_1_content_type: "socks_regular", item_1_volume_level: "medium" as const, item_2_content_type: "bras", item_2_volume_level: "medium" as const, item_3_content_type: "panties", item_3_volume_level: "medium" as const, priority: "convenient" as const, color_preference: "not_important" },
  },
  {
    name: "Wide 120×40×20 — 4 вещи",
    input: { drawer_width_cm: 120, drawer_depth_cm: 40, drawer_height_cm: 20, storage_category: "underwear" as const, items: [{ content_type: "panties", volume_level: "large" as const }, { content_type: "bras", volume_level: "large" as const }, { content_type: "socks_regular", volume_level: "large" as const }, { content_type: "tights", volume_level: "medium" as const }], priority: "convenient" as const, color_preference: "not_important" },
  },
  {
    name: "75×45×15 — forced open fallback",
    input: { drawer_width_cm: 75, drawer_depth_cm: 45, drawer_height_cm: 15, storage_category: "underwear" as const, item_1_content_type: "bras", item_1_volume_level: "medium" as const, item_2_content_type: "socks_regular", item_2_volume_level: "medium" as const, item_3_content_type: "panties", item_3_volume_level: "medium" as const, priority: "convenient" as const, color_preference: "not_important" },
  },
];

// ─── Run ─────────────────────────────────────────────────────────────────────

const catalog = loadCatalog();
console.log(`\nКаталог загружен: ${catalog.length} SKU`);
console.log(`  cells: ${catalog.filter(s => s.division_type === "cells").length}`);
console.log(`  slots: ${catalog.filter(s => s.division_type === "slots").length}`);
console.log(`  open:  ${catalog.filter(s => s.division_type === "open").length}`);
console.log(`  capacity_units=0 (open с null): ${catalog.filter(s => s.capacity_units === 0).length}`);

for (const scenario of scenarios) {
  console.log(`\n${"═".repeat(70)}`);
  console.log(`СЦЕНАРИЙ: ${scenario.name}`);
  console.log("═".repeat(70));

  const output = runUmestnoEngine(scenario.input, { ...defaultLibraries, skuCatalog: catalog });

  if (!output.result) {
    console.log("❌ Движок вернул null (fit failed)");
    continue;
  }

  const products = output.result.products as Array<{
    zone_id: string;
    content_type: string;
    match_status: string;
    candidates: SkuCatalogRow[];
  }>;

  const skuFit = output.result.sku_fit as { sku_fit_status: string };
  console.log(`\nSKU fit status: ${skuFit?.sku_fit_status ?? "—"}`);
  console.log(`Зон: ${products.length}, совпадений: ${products.filter(p => p.match_status === "exact").length}/${products.length}\n`);

  for (const zone of products) {
    const icon = zone.match_status === "exact" ? "✓" : "✗";
    console.log(`  ${icon} ${zone.zone_id} (${zone.content_type}) → ${zone.match_status}`);
    if (zone.candidates.length > 0) {
      const top3 = zone.candidates.slice(0, 3);
      for (const c of top3) {
        const price = c.price_rub != null ? ` ${c.price_rub}₽` : "";
        console.log(`      ${c.sku_id}  ${c.width_cm}×${c.depth_cm}×${c.height_cm}  cap=${c.capacity_units}  ${c.color_group ?? "—"}${price}`);
        console.log(`        ${c.product_title.slice(0, 60)}`);
      }
      if (zone.candidates.length > 3) console.log(`      ... ещё ${zone.candidates.length - 3}`);
    } else {
      // Show why nothing matched
      const zoneInfo = output.result?.scheme?.assigned_zones?.find((z: { zone_id: string }) => z.zone_id === zone.zone_id);
      if (zoneInfo) {
        const relevant = catalog.filter(s => s.division_type === zone.content_type ||
          catalog.find(x => x.division_type === (output.scheme_payload?.selected_calculated_zones?.find((z: { zone_id: string; division_type: string }) => z.zone_id === zone.zone_id)?.division_type)));
        const byType = catalog.filter(s => s.division_type === (output.scheme_payload?.selected_calculated_zones?.find((z: { zone_id: string; division_type: string }) => z.zone_id === zone.zone_id)?.division_type));
        console.log(`      Нет кандидатов. SKU с нужным типом в каталоге: ${byType.length}`);
      }
    }
  }
}

console.log(`\n${"═".repeat(70)}`);
console.log("ДИАГНОСТИКА КАТАЛОГА\n");

// Show open SKUs capacity issue
const openSkus = catalog.filter(s => s.division_type === "open");
console.log(`Open SKU всего: ${openSkus.length}`);
console.log(`  capacity_units=0 (из null): ${openSkus.filter(s => s.capacity_units === 0).length}`);
console.log(`  capacity_units>0: ${openSkus.filter(s => s.capacity_units > 0).length}`);
console.log(`\n⚠ matchSkus фильтрует: capacity_units >= zone.count`);
console.log(`  → open SKU с null capacity не пройдут фильтр`);
console.log(`  → нужно: для open зон capacity_units=null считать как "без ограничений"`);
