#!/usr/bin/env python3
"""Export sku_catalog.db → engine/libraries/skuCatalogData.ts"""
import sqlite3, os, json

REPO_ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
DB_PATH  = os.path.join(REPO_ROOT, "engine", "db", "sku_catalog.db")
OUT_PATH = os.path.join(REPO_ROOT, "engine", "libraries", "skuCatalogData.ts")

conn = sqlite3.connect(DB_PATH)
conn.row_factory = sqlite3.Row
rows = conn.execute("""
    SELECT
        sku_id, division_type, rigidity, set_quantity,
        width_cm, depth_cm, height_cm, can_rotate,
        capacity_units, cell_width_cm, cell_depth_cm,
        color_group, availability_status,
        product_title, product_url, picture_matching,
        seller_or_brand, price
    FROM sku_catalog
    WHERE availability_status != 'unavailable'
      AND division_type IS NOT NULL
    ORDER BY sku_id
""").fetchall()
conn.close()

def val(v):
    if v is None: return "undefined"
    if isinstance(v, (int, float)): return str(v)
    return json.dumps(v)

lines = ["// generated by exportSkuTs.py — do not edit manually",
         "import type { SkuCatalogRow } from '../types.js';",
         "",
         "export const skuCatalogData: SkuCatalogRow[] = ["]

for r in rows:
    d = dict(r)
    fields = ", ".join(
        f"{k}: {val(v)}"
        for k, v in d.items()
        if v is not None and v != "undefined"
    )
    lines.append(f"  {{ {fields} }},")

lines += ["];", ""]

with open(OUT_PATH, "w") as f:
    f.write("\n".join(lines))

print(f"Exported {len(rows)} SKUs to {OUT_PATH}")
