import type { RuleDefinition } from "../types.js";

export const layoutRuleDefinitions: RuleDefinition[] = [
  { rule_id: "ZONE_INTEGRITY", rule_name: "Одна parent zone — один division_type", kind: "layout", when_to_apply: "Всегда для финально размещенных зон.", what_to_do: "Один content_type / parent zone не должен быть разделен между несколькими division_type без явной can_split-семантики.", why: "Схема должна быть объяснимой: одна зона хранения не должна одновременно быть slots/cells/open.", is_hard_rule: true },
  { rule_id: "D01", rule_name: "Одна группа рядом", kind: "layout", when_to_apply: "Если несколько зон имеют одинаковый group_id или ближайшую runtime semantic group/storage_category.", what_to_do: "Держать их рядом, не разносить по разным концам ящика.", why: "Пользователь воспринимает белье как одну смысловую группу.", is_hard_rule: true },
  { rule_id: "D02", rule_name: "Носки не между бельевыми зонами", kind: "layout", when_to_apply: "Если есть носки, трусы и бюстгальтеры.", what_to_do: "Не ставить носки между трусами и бюстгальтерами.", why: "Носки не должны разрывать бельевой блок.", is_hard_rule: true },
  { rule_id: "D03", rule_name: "Раскладывать по ширине / compact main-zone placement", kind: "layout", when_to_apply: "Если в схеме размещается несколько основных зон.", what_to_do: "Основные зоны должны располагаться компактно, с прилеганием друг к другу без случайных внутренних промежутков.", why: "Схема должна выглядеть как цельная конфигурация, а не как случайно разложенные блоки.", is_hard_rule: true },
  { rule_id: "D04", rule_name: "Резерв с краю", kind: "layout", when_to_apply: "Если после размещения зон остается свободное место.", what_to_do: "Свободное место не должно оставаться между основными зонами; оно должно быть вынесено вправо / к краю ящика как reserve-zone.", why: "Пользователь не должен видеть случайные пустые участки в глубине или между блоками.", is_hard_rule: true },
  { rule_id: "D04b", rule_name: "Поглощение глубины", kind: "layout", when_to_apply: "Если после размещения зоны за ней по глубине остается свободный прямоугольник, который не занят другой зоной.", what_to_do: "Репортить возможность увеличить assigned_d до края свободного прямоугольника / до глубины ящика без изменения calculated_d или capacity.", why: "Пользователю полезнее видеть более цельную зону хранения, чем непонятные пустоты за контейнером.", is_hard_rule: false },
  { rule_id: "D05", rule_name: "Ячеистые зоны рядом", kind: "layout", when_to_apply: "Если несколько зон имеют division_type = cells.", what_to_do: "Поставить эти зоны рядом.", why: "Носки, трусы и похожие ячеистые зоны визуально и функционально лучше держать блоком.", is_hard_rule: true },
  { rule_id: "D06", rule_name: "Бюстгальтеры не зажимать", kind: "layout", when_to_apply: "Если есть зона bras.", what_to_do: "Ставить ее с краю бельевого блока или с краю ящика.", why: "Деликатную зону лучше не сжимать с двух сторон.", is_hard_rule: true },
  { rule_id: "D07", rule_name: "Джинсы / крупные folded-вещи сбоку", kind: "layout", when_to_apply: "Если есть джинсы или крупные сложенные вещи.", what_to_do: "Поставить эту зону сбоку, а не в середину мелких зон.", why: "Крупная зона лучше работает как боковой блок.", is_hard_rule: false },
  { rule_id: "D08", rule_name: "Часто используемое ближе к доступной зоне", kind: "layout", when_to_apply: "Если у зоны access_frequency = high.", what_to_do: "Не уводить такую зону в самый неудобный край, если есть выбор.", why: "Часто используемые вещи должны быть легче доступны.", is_hard_rule: false },
  { rule_id: "D09", rule_name: "Folded-вещи держать группой", kind: "layout", when_to_apply: "Если есть несколько зон со storage_method = folded_squares_*.", what_to_do: "Держать их рядом одной стороной.", why: "Сложенные блоки лучше воспринимаются как один текстильный блок.", is_hard_rule: false },
  { rule_id: "D10", rule_name: "Мягкие зоны не под давлением", kind: "layout", when_to_apply: "Если rigidity = soft.", what_to_do: "По возможности не ставить мягкую зону между двумя жесткими / ячеистыми блоками.", why: "Мягкая зона может деформироваться.", is_hard_rule: false }
];

export const fallbackRuleDefinitions: RuleDefinition[] = [
  { rule_id: "FB01", rule_name: "Не пересчитывать всю схему при failed fit", kind: "fallback", when_to_apply: "Если fit_status = fit_partial или fit_none.", what_to_do: "Менять только одну failed/candidate zone за одну итерацию adjustment; не переводить все категории в open сразу.", why: "Локальная правка сохраняет объяснимость схемы и предотвращает нестабильные пересборки.", is_hard_rule: true },
  { rule_id: "FB02", rule_name: "Open fallback только для разрешенных категорий", kind: "fallback", when_to_apply: "Если зона не помещается и alternative_division содержит open.", what_to_do: "Пробовать open только если в B open_fallback_allowed = yes.", why: "Некоторые вещи теряют форму/функцию в открытой секции.", is_hard_rule: true },
  { rule_id: "FB03", rule_name: "Приоритет кандидатов для open", kind: "fallback", when_to_apply: "Если несколько зон можно перевести в open.", what_to_do: "Сортировать кандидатов: failed zones first, затем lower open_fallback_rank, lower open_storage_penalty, сильнее улучшает failed_dimension.", why: "Сначала в open уходят более гибкие и менее структурно чувствительные вещи.", is_hard_rule: false },
  { rule_id: "FB04", rule_name: "Open считается от свободного прямоугольника", kind: "fallback", when_to_apply: "Если выбран open fallback.", what_to_do: "Оставить уже размещенные совместимые зоны на месте; взять оставшийся available_box / reserve_box и считать open_capacity внутри него.", why: "Open — box-first, not count-first: зона не пересчитывается от count, а проверяет вместимость доступного контейнера.", is_hard_rule: true },
  { rule_id: "FB05", rule_name: "Принимать open только если вместимости хватает", kind: "fallback", when_to_apply: "Если создан open fallback candidate.", what_to_do: "Accept only if open_capacity >= required_count, height fits, hard rules are not violated, and failed_dimension improves.", why: "Open fallback должен хранить весь нужный объем и реально улучшать fit.", is_hard_rule: true }
];
