CREATE TABLE IF NOT EXISTS sku_catalog (
  sku_id               TEXT PRIMARY KEY,
  source_platform      TEXT,
  seller_or_brand      TEXT,
  product_title        TEXT,
  product_url          TEXT,
  picture_matching     TEXT,
  division_type        TEXT NOT NULL,
  rigidity             TEXT,
  storage_use_case     TEXT,
  set_quantity         REAL NOT NULL DEFAULT 1,
  width_cm             REAL,
  depth_cm             REAL,
  height_cm            REAL,
  can_rotate           TEXT,
  cols                 INTEGER,
  rows                 INTEGER,
  capacity_units       REAL,
  capacity_basis       TEXT,
  cell_width_cm        REAL,
  cell_depth_cm        REAL,
  color_raw            TEXT,
  color_normalized     TEXT,
  color_group          TEXT,
  color_confidence     TEXT,
  material_raw         TEXT,
  material_normalized  TEXT,
  material_group       TEXT,
  material_confidence  TEXT,
  has_lid              TEXT,
  has_bottom           TEXT,
  foldable             TEXT,
  adjustable           TEXT,
  modular              TEXT,
  cuttable             TEXT,
  price                REAL,
  currency             TEXT,
  availability_status  TEXT,
  last_checked_date    TEXT,
  quality_notes        TEXT,
  fit_risk_notes       TEXT,
  source_confidence    TEXT
);
